### PR TITLE
Add endive benchmarks

### PR DESCRIPTION
**Pull request by rodrigo7491**
This PR adds the [endive](https://github.com/informalsystems/tla-files/tree/main/examples/endive-artifact/apalache) benchmarks to the `performance` project. Their timeout is set to 2h, in accordance with the other comparison benchmarks already present in the project.

### CODE REVIEW

**Review by shonfeder — APPROVED** [review]
LGTM! 

Thanks :)

**Comment by rodrigo7491** [comment]
@shonfeder the workflow with the new benchmarks was cancelled after 6 hours as I feared. I imagine that if we merge the PR the automatic runs from now on will all fail, which is not ideal. My suggestion is to make a new project with benchmarks (endive plus future additions) that are only run manually, and possibly locally instead of on GitHub. What do you think?

**Comment by shonfeder** [comment]
We'll need to work on breaking the bench tests into parallel runs or setting up our own runners now!

**Comment by shonfeder** [comment]
Sorry I missed your message here before merging! I agree that  the way to fix this is probably to break things into smaller projects, then run those separately. I think we should be able to run each project on a different runner, so still be able to run them via actions.

**Pull request merged**
