### PR TITLE
Add new project with 2PCwithBTM spec

### PR DESCRIPTION
**Pull request by rodrigo7491**
This PR is a follow up of #53, adding a 4th project. Currently upon running `sbt examples/benchmarksReport` an exception is thrown stating that no tests were run, because the files with the specs were not found.

`suiteForEncoding_2PCwithBTM` is similar to `suiteForEncoding_endive` from #52. The `.xml` and `.yml` that are generate seem to have right path, as far as I can tell. Running `sbt clean` did not make any difference. Can you see if you can reproduce this @shonfeder?

### CODE REVIEW

**Comment by shonfeder** [comment]
So my guess about what's happening here:

- The file name generated for the `yml` file here is quite long, and is causing the pretty printing of the generated HTML to insert newlines before and after the xml tags.
- benchexec doesn't trim or sanitize the value in this xml field in the way we might want/expect, so it's including those newlines in the file name :/

This is how the file is being rendered via the pretty printer:

```
    <include>
      005TwoPCwithBTMSuite-apalache-001-run-MC4_FALSE_FALSE.tla-task-MC4_FALSE_FALSE.tla.yml
    </include>
```

**Comment by shonfeder** [comment]
Should be fixed by https://github.com/informalsystems/apalache-bench/pull/56

**Comment by rodrigo7491** [comment]
This PR adds the first spec of the `examples` project, more specs will be added to this project later. The exception previously mentioned was solved by #56, so the PR can now be merged safely.

**Review by shonfeder — APPROVED** [review]
LGTM!

**Comment by shonfeder** [comment]
@rodrigo7491 are you ready for us to merge this in?

**Comment by rodrigo7491** [comment]
Waiting on #57.

**Pull request merged**
